// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b08baf8a-8de9-45bc-a2d8-d537e23d2426",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_B4xlOmGS0",
    "aws_user_pools_web_client_id": "6b96cs2pmq0khunn6mth7r48td",
    "oauth": {},
    "aws_user_files_s3_bucket": "platformfile-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;