import { NgModule } from '@angular/core';
import {
  MatFormFieldModule,
  MatIconModule,
  MatInputModule,
  MatButtonModule,
  MatListModule,
  MatCardModule,
  MatDialogModule,
  MatToolbarModule,
  MatChipsModule,
  MatDatepickerModule,
  MatSidenavModule,
  MatTabsModule,
  MatSortModule,
  MatProgressBarModule,
  MatMenuModule,
  MatAutocompleteModule,
  MatRadioModule,
  MatPaginatorModule,
  MatExpansionModule,
  MatSelectModule,
  MatSnackBarModule,
  MatProgressSpinnerModule,
  MatStepperModule
} from '@angular/material';
import {MatTableModule} from '@angular/material/table';
import { CdkAccordionModule } from '@angular/cdk/accordion';


@NgModule({
  declarations: [],
  imports: [
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatButtonModule,
    MatListModule,
    MatCardModule,
    MatDialogModule,
    MatToolbarModule,
    MatChipsModule,
    MatDatepickerModule,
    MatTableModule,
    MatSidenavModule,
    MatTabsModule,
    MatSortModule,
    MatProgressBarModule,
    MatMenuModule,
    MatAutocompleteModule,
    MatRadioModule,
    MatPaginatorModule,
    MatExpansionModule,
    MatSelectModule,
    CdkAccordionModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatStepperModule
  ],
  exports: [
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatButtonModule,
    MatListModule,
    MatCardModule,
    MatDialogModule,
    MatToolbarModule,
    MatChipsModule,
    MatDatepickerModule,
    MatTableModule,
    MatSidenavModule,
    MatTabsModule,
    MatSortModule,
    MatProgressBarModule,
    MatMenuModule,
    MatAutocompleteModule,
    MatRadioModule,
    MatPaginatorModule,
    MatExpansionModule,
    MatSelectModule,
    CdkAccordionModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatStepperModule
  ]
})
export class MaterialModule {}
